name: deploy

on:
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:
    types:
    - deploy

jobs:
  build-deploy:
    uses: geolexica/ci/.github/workflows/site-deploy-github-pages.yml@main
    with:
      ref: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.ref || github.ref }}
      repository: geolexica/osgeo-glossary
      concepts-path: osgeo-glossary
      production-branch: refs/heads/main
      production-url: https://osgeo.geolexica.org
